- hosts: test
  become: yes
  tasks:
    - name: Set up Teleport Agent
      shell: |
        sudo bash -c "$(curl -fsSL https://test.joeshiett.xyz/scripts/d53e2a879774ce11fa19a4ba8aabcd8b/install-node.sh)"
    