---
- hosts: teleport
  become: yes
  tasks: 
    - name: Update the apt package index
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install packages for apt add repository over HTTPS
      become: yes
      apt:
        name: "{{ packagesdep }}"
        force_apt_get: yes
        state: latest
        update_cache: yes
      vars:
        packagesdep:
          - git
          - apt-transport-https
          - ca-certificates
          - wget
          - software-properties-common
          - gnupg2
          - curl

    - name: Add Teleport GPG public key
      become: yes
      apt_key:
        url: https://deb.releases.teleport.dev/teleport-pubkey.asc
        state: present

    - name: add Teleport official repository
      become: yes
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] https://deb.releases.teleport.dev/ stable main
        state: present
    
    - name: Index new repo into the cache
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: install Teleport
      become: yes
      apt:
        name: teleport
        state: latest
        update_cache: yes
     
    # - name: Install Teleport
    #   shell: |
    #     sudo curl https://deb.releases.teleport.dev/teleport-pubkey.asc \
    #     -o /usr/share/keyrings/teleport-archive-keyring.asc
    #     echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] https://deb.releases.teleport.dev/ stable main" \
    #     | sudo tee /etc/apt/sources.list.d/teleport.list > /dev/null
    #     sudo apt-get update
    #     sudo apt-get install teleport
      
    #   chdir: /home/ap
